language: python

python:
  - '3.8'
  - '3.7'

install:
- pip install -e .
- pip install -r requirements-dev.txt

script:
- python ./setup.py develop && COMPILE='--compile' make check

# blacklist
branches:
  except:
    - data-driven-pytest
